sass:
  sass_dir: assets/_scss
  style: compressed

markdown: kramdown

kramdown:
  parse_block_html: false

exclude:
- README.md
- Makefile
- wiki
- en/od-faq.md

# site configuration
multilingual: true
base: http://opendatatoolkit.worldbank.org

# default values
defaults:
-
  scope:
    path: ""
  values:
    layout: default
    pageCategory: "content page"
    contentType: "Learning"
-
  scope:
    path: "en"
  values:
    locale: en
-
  scope:
    path: "es"
  values:
    locale: es
-
  scope:
    path: "fr"
  values:
    locale: fr

# language localization
lang:
  locales:
    - [ en, English ]
    - [ es, Espa&ntilde;ol ]
    - [ fr, Fran&ccedil;ais ]

  en:
    title: "World Bank Open Government Data Toolkit"
    description: "The Open Government Data Toolkit is designed to help governments, Bank staff and users understand the basic precepts of Open Data, then get \"up to speed\" in planning and implementing an open government data program, while avoiding common pitfalls."
    abstract:    "The Open Government Data Toolkit is designed to help governments, Bank staff and users understand the basic precepts of Open Data, then get \"up to speed\" in planning and implementing an open government data program, while avoiding common pitfalls."
    localeprefix: "This page in"
    sidebar:
      - {hdr: h2, link: /en/index.html, title: Open Government Data Toolkit }
      - {hdr: h3, link: /en/open-data-in-60-seconds.html, title: Open Data in 60 Seconds }
      - {hdr: h3, link: /en/essentials.html, title: Open Data Essentials }
      - {hdr: h3, link: /en/starting.html, title: Starting an Open Data Initiative }
      - {hdr: h3, link: /en/technology.html, title: Technology Options }
      - {hdr: h3, link: /en/demand.html, title: Demand and Engagement }
      - {hdr: h3, link: /en/supply.html, title: Supply and Quality of Data }
      - {hdr: h3, link: /en/odra.html, title: Readiness Assessment Tool }
      - {hdr: h3, link: /en/technical-assistance.html, title: Technical Assistance and Funding }

  es:
    title: "Conjunto de Herramientas de Datos Abiertos de Gobierno"
    description: "El conjunto de herramientas sobre datos abiertos de gobierno está diseñado para ayudar a los Gobiernos, el personal del Banco y los usuarios a entender los preceptos básicos de los datos abiertos, de modo de agilizar la planificación y la implementación de un programa de este tipo y evitar las dificultades más comunes."
    abstract:    "El conjunto de herramientas sobre datos abiertos de gobierno está diseñado para ayudar a los Gobiernos, el personal del Banco y los usuarios a entender los preceptos básicos de los datos abiertos, de modo de agilizar la planificación y la implementación de un programa de este tipo y evitar las dificultades más comunes."
    localeprefix: "Esta página en"
    sidebar:
      - {hdr: h2, link: /es/index.html, title: Caja de Herramientas de Datos Abiertos de Gobierno }
      - {hdr: h3, link: /es/open-data-in-60-seconds.html, title: Datos Abiertos en 60 segundos }
      - {hdr: h3, link: /es/essentials.html, title: Aspectos fundamentales de los Datos Abiertos }
      - {hdr: h3, link: /es/starting.html, title: Cómo empezar una iniciativa de Datos Abiertos de gobierno }
      - {hdr: h3, link: /es/technology.html, title: Opciones tecnológicas }
      - {hdr: h3, link: /es/demand.html, title: Demanda y participación }
      - {hdr: h3, link: /es/supply.html, title: Oferta y calidad de los datos }
      - {hdr: h3, link: /es/odra.html, title: Herramienta de evaluación del grado de preparación }
      - {hdr: h3, link: /es/technical-assistance.html, title: Asistencia técnica y financiamiento }

  fr:
    title: "World Bank Open Government Data Toolkit"
    description: "Le Guide pratique de l’Open Data a pour but d’aider les pouvoirs publics, le personnel de la Banque mondiale et les utilisateurs à comprendre les principes fondamentaux de l'ouverture des données publiques, et à planifier et mettre en œuvre un programme de ce type en évitant les écueils les plus courants."
    abstract:    "Le Guide pratique de l’Open Data a pour but d’aider les pouvoirs publics, le personnel de la Banque mondiale et les utilisateurs à comprendre les principes fondamentaux de l'ouverture des données publiques, et à planifier et mettre en œuvre un programme de ce type en évitant les écueils les plus courants."
    localeprefix: "Cette page en"
    sidebar:
      - {hdr: h2, link: /fr/index.html, title: Guide pratique de l'Open Data }
      - {hdr: h3, link: /fr/open-data-in-60-seconds.html, title: L'Open Data en 60 secondes }
      - {hdr: h3, link: /fr/essentials.html, title: Ce qu'il faut savoir }
      - {hdr: h3, link: /fr/starting.html, title: Premiers jalons }
      - {hdr: h3, link: /fr/technology.html, title: Options technologiques }
      - {hdr: h3, link: /fr/demand.html, title: Demande et mobilisation du public }
      - {hdr: h3, link: /fr/supply.html, title: Offre et qualité des données }
      - {hdr: h3, link: /fr/odra.html, title: Outil d'évaluation de la maturité }
      - {hdr: h3, link: /fr/technical-assistance.html, title: Assistance technique et financement }

